/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 18 19:29:19 GMT 2023
 */

package sg.edu.nus.comp.cs4218.impl.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedOutputStream;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.SequenceInputStream;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.jupiter.api.extension.RegisterExtension;
import sg.edu.nus.comp.cs4218.impl.app.EchoApplication;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class EchoApplication_ESTest extends EchoApplication_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(EchoApplication_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      String[] stringArray0 = new String[4];
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("4W$cUBy'ihPfZPC(C ");
      echoApplication0.run(stringArray0, (InputStream) null, mockFileOutputStream0);
      assertEquals(4, stringArray0.length);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      String[] stringArray0 = new String[8];
      byte[] byteArray0 = new byte[4];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(byteArrayInputStream0, byteArrayInputStream0);
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      try { 
        echoApplication0.run(stringArray0, sequenceInputStream0, pipedOutputStream0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // echo: IOException
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.EchoApplication", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      String[] stringArray0 = new String[7];
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      BufferedOutputStream bufferedOutputStream0 = new BufferedOutputStream((OutputStream) null);
      MockPrintStream mockPrintStream0 = new MockPrintStream(bufferedOutputStream0, true);
      // Undeclared exception!
      try { 
        echoApplication0.run(stringArray0, pipedInputStream0, mockPrintStream0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.BufferedOutputStream", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      try { 
        echoApplication0.constructResult((String[]) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // echo: Null arguments
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.EchoApplication", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test4()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      String[] stringArray0 = new String[4];
      try { 
        echoApplication0.run(stringArray0, (InputStream) null, (OutputStream) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // echo: OutputStream not provided
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.EchoApplication", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test5()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      String[] stringArray0 = new String[1];
      String string0 = echoApplication0.constructResult(stringArray0);
      assertEquals("null\r\n", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test6()  throws Throwable  {
      EchoApplication echoApplication0 = new EchoApplication();
      String[] stringArray0 = new String[0];
      String string0 = echoApplication0.constructResult(stringArray0);
      assertEquals("\r\n", string0);
  }
}
